### PR TITLE
Upgrade to Neo4j 4.0.0 driver.

### PR DESCRIPTION
**Pull request by michael-simons**
Hey everyone.

Neo4j's 4.0 driver are out and with them, native reactive access to the upcoming 4.0.0 release. @graemerocher and I spoke already about them and I had a look how you use the Neo4j driver in Micronaut and I prepared a PR for an upgrade. 

Be aware that this is probably nothing for a patch release, as the 4.0 line has breaking API changes in contrast to the 1.7.x line. But: 4.0 is needed to access 4.0. I guess you could bring this in in a Minor. The API mostly changed packages. The different types of accessible sessions are now better structured and the name of the result set classes etc. now match those of JDBC more. Have a look here: https://neo4j.com/docs/driver-manual/4.0-preview/session-api/

One major benefit of our 4.0.0 driver: It supports native compilation on the GraalVM ootb.

I didn't touch the embedded support yet. That will require a bit more work. Below, find more details of the one commit message.

Cheers,
Michael

This commit has 3 aspects, the upgrade to the Neo4j 4.0.0 driver being
the primary concern.

For the upgrade package imports needed to be fixed and one of the
builder methods of the Neo4j bolt configuration needed a small change.

As we distinguish now between three session types, those sessions live
in different packages as well.

As the asynchronous session has been used for the Health check, that
needed to be fixed as well.

The health indicator is the second aspect. The composition of the
query and results can be simplified. Also we should use a write
transaction, in case we are in a cluster scenario. A read transaction
would only indicate general health but a status of `UP` would not
guarantee writes to succede.
At the same position, we strongly recommends against counting nodes for
health and propose returning some info about the server itself.

Last but not least, the driver has build-in slf4 logging, so that the
anonymous inner class can just be dropped.

### CODE REVIEW

**Comment by graemerocher** [comment]
@michael-simons Thanks for the contribution! I think it is indeed best to release a new major version of the driver module as making changes like this in a patch release would be a breaking change from our end.

However, thanks for undertaking the driver upgrade and improving the health check, the changes look good. I will merge soon.

**Comment by graemerocher** [comment]
I have merged this into master which is now set to 2.0.0 snapshot. Thanks for the contribution.

**Comment by michael-simons** [comment]
Great news, Graeme! Thank you. Let me know if and when you're interested in pairing or discussing reactive Neo4j support in Micronaut, too, now that the basics (aka 4.0 driver and 4.0 database) are available.

**Comment by graemerocher** [comment]
@michael-simons sounds awesome, maybe DM me on twitter and we can setup a call?

**Pull request merged**
